In [1]:
import nltk


In [4]:
from nltk.stem.porter import PorterStemmer

from nltk.stem import WordNetLemmatizer

import re

from nltk.corpus import stopwords

In [5]:
para="""One day, a poor boy who was selling goods from door to door to pay his way through school, found he had only one thin dime left, and he was hungry.

He decided he would ask for a meal at the next house. However, he lost his nerve when a lovely young woman opened the door. Instead of a meal he asked for a drink of water. She thought he looked hungry so brought him a large glass of milk. He drank it slowly, and then asked, “How much do I owe you?”

“You don’t owe me anything,” she replied “Mother has taught us never to accept payment for a kindness.” He said… “Then I thank you from my heart.” His name was Howard Kelly.

As Howard Kelly left that house, he not only felt; stronger physically, but his faith in God and man was strong also. He had been ready to give up and quit.

Years later that young woman became critically ill. The local doctors were baffled. They finally sent her to the big city, where they called in specialists to study her rare disease. Dr. Howard Kelly was called in for the consultation. When he heard the name of the town she came from, a strange light filled his eyes.

Immediately he rose and went down the hall of the hospital to her room. Dressed in his doctor’s gown he we nt in to see her. He recognized her at once. He went back to the consultation room determined to do his best to save her life. From that day he gave special attention to the case.

After a long struggle, the battle was won. Dr. Kelly requested the business office to pass the final bill to him for approval. He looked at it, then wrote something on the edge and the bill was sent to her room."""

In [6]:
sentences=nltk.sent_tokenize(para)
sentences

['One day, a poor boy who was selling goods from door to door to pay his way through school, found he had only one thin dime left, and he was hungry.',
 'He decided he would ask for a meal at the next house.',
 'However, he lost his nerve when a lovely young woman opened the door.',
 'Instead of a meal he asked for a drink of water.',
 'She thought he looked hungry so brought him a large glass of milk.',
 'He drank it slowly, and then asked, “How much do I owe you?”\n\n“You don’t owe me anything,” she replied “Mother has taught us never to accept payment for a kindness.” He said… “Then I thank you from my heart.” His name was Howard Kelly.',
 'As Howard Kelly left that house, he not only felt; stronger physically, but his faith in God and man was strong also.',
 'He had been ready to give up and quit.',
 'Years later that young woman became critically ill.',
 'The local doctors were baffled.',
 'They finally sent her to the big city, where they called in specialists to study her rare d

In [11]:
ps=PorterStemmer()


corpus_stem=[]
for i in range(len(sentences)):
    review=re.sub('[^a-zA-Z]' ,' ',sentences[i])
    review=review.lower()
    review=review.split()
    review=[ps.stem(word)  for word in review if word not in set(stopwords.words('english'))]
    review=' '.join(review)
    corpus_stem.append(review)

In [12]:
corpus_stem

['one day poor boy sell good door door pay way school found one thin dime left hungri',
 'decid would ask meal next hous',
 'howev lost nerv love young woman open door',
 'instead meal ask drink water',
 'thought look hungri brought larg glass milk',
 'drank slowli ask much owe owe anyth repli mother taught us never accept payment kind said thank heart name howard kelli',
 'howard kelli left hous felt stronger physic faith god man strong also',
 'readi give quit',
 'year later young woman becam critic ill',
 'local doctor baffl',
 'final sent big citi call specialist studi rare diseas',
 'dr howard kelli call consult',
 'heard name town came strang light fill eye',
 'immedi rose went hall hospit room',
 'dress doctor gown nt see',
 'recogn',
 'went back consult room determin best save life',
 'day gave special attent case',
 'long struggl battl',
 'dr kelli request busi offic pass final bill approv',
 'look wrote someth edg bill sent room']

In [13]:
lem=WordNetLemmatizer()

corpus_lem=[]
for j in range(len(sentences)):
    review=re.sub('[^a-zA-Z]',' ',sentences[j])
    review=review.lower()
    review=review.split()
    review=[lem.lemmatize(word)  for word in review if word not in set(stopwords.words('english'))]
    review=' '.join(review)
    corpus_lem.append(review)

In [14]:
corpus_lem

['one day poor boy selling good door door pay way school found one thin dime left hungry',
 'decided would ask meal next house',
 'however lost nerve lovely young woman opened door',
 'instead meal asked drink water',
 'thought looked hungry brought large glass milk',
 'drank slowly asked much owe owe anything replied mother taught u never accept payment kindness said thank heart name howard kelly',
 'howard kelly left house felt stronger physically faith god man strong also',
 'ready give quit',
 'year later young woman became critically ill',
 'local doctor baffled',
 'finally sent big city called specialist study rare disease',
 'dr howard kelly called consultation',
 'heard name town came strange light filled eye',
 'immediately rose went hall hospital room',
 'dressed doctor gown nt see',
 'recognized',
 'went back consultation room determined best save life',
 'day gave special attention case',
 'long struggle battle',
 'dr kelly requested business office pas final bill approval'

# creating bags of words using CountVectorizer

In [15]:
from sklearn.feature_extraction.text import CountVectorizer
CV=CountVectorizer()
x_lem=CV.fit_transform(corpus_lem).toarray()

In [16]:
x_lem

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [17]:
x_lem.shape

(21, 126)

In [18]:
x_stem=CV.fit_transform(corpus_stem).toarray()

In [19]:
x_stem

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int64)

In [20]:
x_stem.shape

(21, 125)

# Creating bag of words using TDIF

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf=TfidfVectorizer()
tfidf_lem=tf.fit_transform(corpus_lem).toarray()
tfidf_lem

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.32535569],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.40960308, 0.        ,
        0.        ]])

In [22]:
tfidf_stem=tf.fit_transform(corpus_stem).toarray()
tfidf_stem

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.32535569],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.40960308, 0.        ,
        0.        ]])